--- #YAML:1.0
name:                POE-Component-IRC-Plugin-PAUSE-RecentUploads
version:             0.01
abstract:            PoCo::IRC plugin
license:             ~
author:              
    - zoffix <zoffix@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          1.04
    POE:                           0.9999
    POE::Component::IRC::Plugin:   0.09
    POE::Component::WWW::PAUSE::RecentUploads::Tail: 0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
